# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041a\u0430\u0444\u0435\u0434\u0440\u0430, \u0433\u0440\u0443\u043f\u043f\u0430, \u0433\u043e\u0434')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u0430?')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Department', verbose_name='\u041a\u0430\u0444\u0435\u0434\u0440\u0430 \u0438 \u0433\u0440\u0443\u043f\u043f\u0430'),
        ),
    ]
