# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170131_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '\u041a\u0430\u0444\u0435\u0434\u0440\u0430', 'verbose_name_plural': '\u041a\u0430\u0444\u0435\u0434\u0440\u044b'},
        ),
    ]
