# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u0435\u0440\u0432\u044b\u0439 \u0432\u043e\u043f\u0440\u043e\u0441?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question_2',
            field=models.TextField(blank=True, null=True, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0439 \u0432\u043e\u043f\u0440\u043e\u0441?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question_3',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0440\u0435\u0442\u0438\u0439 \u0432\u043e\u043f\u0440\u043e\u0441???'),
        ),
    ]
