# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20170218_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f \u043f\u043e \u0441\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u044e \u043a\u0443\u0440\u0441\u0430:'),
        ),
    ]
