# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20170219_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question_2',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f \u043f\u043e \u043e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u0438 \u043a\u0443\u0440\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question_3',
            field=models.TextField(blank=True, null=True, verbose_name='\u041b\u0438\u0447\u043d\u044b\u0435 \u0438\u043d\u0442\u0435\u0440\u0435\u0441\u044b'),
        ),
    ]
