# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20170219_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='question_4',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u043d\u044b \u043d\u0430 \u0431\u0443\u0434\u0443\u0449\u0435\u0435'),
        ),
    ]
