# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_question_right_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432\u0435\u0440\u043d\u043e\u0433\u043e \u043e\u0442\u0432\u0435\u0442\u0430'),
        ),
    ]
