# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20170201_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learning.Test', verbose_name='\u0422\u0435\u0441\u0442'),
            preserve_default=False,
        ),
    ]
