# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20170204_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question'),
        ),
    ]
