# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_answer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answer'),
        ),
    ]
