# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20170206_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='material')),
                ('name', models.CharField(max_length=256, verbose_name='\u0418\u043c\u044f \u0444\u0430\u0439\u043b\u0430')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.Discipline', verbose_name='\u0414\u0438\u0441\u0446\u0438\u043f\u043b\u0438\u043d\u0430')),
            ],
        ),
    ]
