# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:09
from __future__ import unicode_literals

import core.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': '\u041f\u043e\u043b\u0435\u0437\u043d\u044b\u0439 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b', 'verbose_name_plural': '\u041f\u043e\u043b\u0435\u0437\u043d\u044b\u0435 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044b'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.base.PathAndRename(b'answer')),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='image',
            field=models.ImageField(upload_to=core.base.PathAndRename(b'discipline')),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to=core.base.PathAndRename(b'material')),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.base.PathAndRename(b'question')),
        ),
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(upload_to=core.base.PathAndRename(b'test')),
        ),
    ]
